apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-veiviser
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-veiviser-ny/sosialhjelp-veiviser-ny:{{version}}
  port: 8080
  accessPolicy:
    outbound:
      external:
        - host: "appres.nav.no"
        - host: "nav.psplugin.com"
      rules: []
{{#if openForLabsInbound}}
    inbound:
      external:
        - host: "sosialhjelp-test-proxy.labs.nais.io"
{{/if}}
  ingresses:
{{#each ingresses}}
   - "{{this}}"
{{/each}}
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /prometheus
  liveness:
    path: /sosialhjelp/internal/isAlive
    initialDelay: 20
  readiness:
    path: /sosialhjelp/internal/isAlive
    initialDelay: 20
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  webproxy: {{webProxyEnabled}}
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
