apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}
  namespace: {{namespace}}
  labels:
    team: digisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-veiviser-ny/sosialhjelp-veiviser-ny:{{version}}
  port: 8080
  ingresses:
{{#each ingresses}}
   - "{{this}}"
{{/each}}
  prometheus:
    enabled: true
    path: /prometheus
  liveness:
    path: sosialhjelp/internal/isAlive
    initialDelay: 20
    port: 8080
  readiness:
    path: sosialhjelp/internal/isReady
    initialDelay: 20
    port: 8080
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
