version: 2

jobs:
    build:
        docker: 
            - image: circleci/node:latest
          steps:
            - checkout
    deploy_miljo:
        docker:
            - image: navikt/deployment:v1
        steps:
            - checkout
            - run:
                  name: Deploy versjon=${VERSION} til miljø=${MILJO} i dev-sbs
                  command: |
                      git clone https://github.com/navikt/sosialhjelp-ci.git
                      VERSION=$(sosialhjelp-ci/bin/create-artifact-version.sh)
                      yq w nais/dev/${MILJO}.json version "${VERSION}" | yq r -j - > deployment.json
                      /app/deploy \
                          --apikey="$NAIS_DEPLOY_APIKEY" \
                          --cluster="dev-sbs" \
                          --repository="$CIRCLE_PROJECT_REPONAME" \
                          --resource="nais.yaml" \
                          --vars="deployment.json" \
                          --wait=true

    deploy_miljo_tag:
        docker:
            - image: navikt/deployment:v1
        steps:
            - checkout
            - run:
                  name: Deploy til miljø i dev-sbs
                  command: |
                      git clone https://github.com/navikt/sosialhjelp-ci.git
                      yq w "nais/dev/${MILJO}.json" version "${TAG}" > deployment.yaml

                      /app/deploy \
                          --apikey="$NAIS_DEPLOY_APIKEY" \
                          --cluster="dev-sbs" \
                          --repository="$CIRCLE_PROJECT_REPONAME" \
                          --resource="nais.yaml" \
                          --vars="deployment.yaml" \
                          --wait=true
    deploy_prod_tag:
        docker:
            - image: navikt/deployment-cli:0.4.0
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Deploy versjon=${VERSION} til prod
                  command: |
                      deployment-cli deploy create --cluster=prod-sbs --repository=navikt/sosialhjelp-veiviser-ny --team=digisos -r=nais.yaml --var version=${TAG} --vars=nais/prod/default.json

    deploy_prod:
        docker:
            - image: navikt/deployment-cli:v0.2.0
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Deploy versjon=${VERSION} til prod
                  command: |
                      git clone https://github.com/navikt/sosialhjelp-ci.git
                      VERSION=$(sosialhjelp-ci/bin/create-artifact-version.sh)
                      deployment-cli deploy create --cluster=prod-sbs --repository=navikt/$CIRCLE_PROJECT_REPONAME --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/prod/default.json

    deploy_gcp:
        docker:
            - image: navikt/deployment:v1
        steps:
            - checkout
            - run:
                  name: Deploy til miljø i gcp
                  command: |
                      yq w nais/dev/${MILJO}.json version "${TAG}" > deployment.yaml
                      /app/deploy \
                          --apikey="$NAIS_DEPLOY_APIKEY" \
                          --cluster="${MILJO}" \
                          --repository="$CIRCLE_PROJECT_REPONAME" \
                          --resource="nais.yaml" \
                          --vars="deployment.yaml" \
                          --wait=true
